[mgr]
ratio = [1, 2, 5]
show_hidden = true

[plugin]
prepend_fetchers = [
  { id   = "git", name = "*", run  = "git" },
  { id   = "git", name = "*/", run  = "git" },
]
prepend_previewers = [
  { url = "*/", run = "mux eza_tree_1 eza_tree_2 eza_tree_3 eza_tree_4" },
  { url = "*.csv", run = "mux code duckdb" },
  { url = "*.tsv", run = "mux code duckdb" },
  { url = "*.json", run = "mux code duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.txt", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },

  { url = "*.npy", run = 'piper -- num-peek "$1"' },
]
prepend_preloaders = [
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false },
]
